import React from "react";
import { EmployeeWarning } from "@/types";

// What the employee hears for each kind (telephony/asterisk/sounds, generated by make_warning_sounds.py)
const SPOKEN: Record<string, string> = {
  otp: "تنبيه، المتصل بيطلب كود التحقق، متدّيهوش.",
  secret: "تنبيه، المتصل بيطلب بيانات سرية، متقولهاش.",
  payment: "تنبيه، المتصل بيطلب تحويل فلوس، متحوّلش.",
  remote: "تنبيه، المتصل عايزك تنزّل برنامج تحكم، متنزّلوش.",
  impersonation: "تنبيه، المتصل ممكن ينتحل صفة البنك، اتأكد منه.",
  pressure: "تنبيه، المتصل بيضغط عليك، خد وقتك.",
  general: "تنبيه، احتمال نصب في المكالمة، خلّي بالك.",
};

/** Spoken warnings already played into the employee's ear on this call (the caller hears nothing). */
export const EmployeeWarnings: React.FC<{ warnings: EmployeeWarning[] }> = ({ warnings }) => {
  if (warnings.length === 0) return null;
  return (
    <div className="bg-amber-950/50 border border-amber-700 rounded-xl p-4 mb-6">
      <h3 className="text-amber-300 text-xs font-semibold uppercase tracking-wider mb-2">
        Spoken warning sent to the employee
      </h3>
      <ul className="space-y-1">
        {warnings.map((w, i) => (
          <li key={i} className="flex justify-between items-center gap-4">
            <span dir="rtl" className="text-base text-amber-50">🔊 {SPOKEN[w.kind] ?? w.kind}</span>
            <span className="text-[11px] font-mono text-amber-400/70">
              {w.kind} · {new Date(w.at).toLocaleTimeString()}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
};
