"""Voice-cloning fakes for the anti-spoofing test set: the 105 Test 2 sentences, on a Modal GPU.

  xtts    XTTS-v2 (coqui/XTTS-v2), Arabic, two of its built-in studio voices (one male, one female)
  egtts   EGTTS-V0.1 (OmarSamir/EGTTS-V0.1, XTTS-v2 fine-tuned on Egyptian Arabic), cloning a reference voice

No real person's voice is cloned: EGTTS's reference clip is itself generated by XTTS from a built-in voice
(the speaker_reference.wav shipped with EGTTS is not used). Model licence: Coqui Public Model License
(non-commercial) - fine for this research test, not for a product.

Run from the repo root, then add the clips to the test set:
  modal run ml/antispoof/testset/modal_clone_tts.py
  ml/asr/.venv/Scripts/python ml/antispoof/testset/make_testset.py --only xtts,egtts \
      --add xtts=ml/antispoof/testset/_clone/xtts --add egtts=ml/antispoof/testset/_clone/egtts
"""

import json
from pathlib import Path

import modal

HERE = Path(__file__).resolve().parent  # repo paths are only used locally, in main()
VOICES = {"male": "Damien Black", "female": "Ana Florence"}  # XTTS-v2 built-in speakers
REFERENCE_TEXT = ("أهلا بحضرتك، معاك خدمة العملاء. ممكن حضرتك تقولي الاسم بالكامل ورقم الحساب "
                  "عشان أقدر أساعدك في الطلب بتاعك النهارده؟")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("ffmpeg")
    .pip_install("torch<2.9", "torchaudio<2.9")
    .pip_install("coqui-tts", "transformers>=4.47,<5", "huggingface_hub", "soundfile")
)
app = modal.App("ecfd-antispoof-clone-tts")


def _load(repo: str, config_repo: str = None):
    import os

    from huggingface_hub import snapshot_download
    from TTS.tts.configs.xtts_config import XttsConfig
    from TTS.tts.models.xtts import Xtts

    path = snapshot_download(repo)
    config = XttsConfig()
    try:
        config.load_json(os.path.join(path, "config.json"))
    except Exception as e:  # EGTTS's config.json is reported as malformed: use the base XTTS-v2 config
        print(f"[{repo}] config.json unreadable ({e}); using {config_repo}'s")
        config.load_json(os.path.join(snapshot_download(config_repo), "config.json"))
    model = Xtts.init_from_config(config)
    model.load_checkpoint(config, checkpoint_dir=path, vocab_path=os.path.join(path, "vocab.json"),
                          use_deepspeed=False)
    model.cuda()
    model.eval()  # coqui's eval() returns None, so don't chain it
    return model


def _wav_bytes(samples, rate=24000) -> bytes:
    import io

    import numpy as np
    import soundfile as sf

    buf = io.BytesIO()
    sf.write(buf, np.asarray(samples, dtype="float32"), rate, format="WAV")
    return buf.getvalue()


@app.function(image=image, gpu="A10G", timeout=3600)
def generate(sentences: dict) -> dict:
    """{turn: text} -> {"xtts/<turn>": wav bytes, "egtts/<turn>": wav bytes}. Voices alternate male/female by turn."""
    import os
    import tempfile

    import torch

    out = {}
    xtts = _load("coqui/XTTS-v2")
    latents = {g: xtts.speaker_manager.speakers[name] for g, name in VOICES.items()}
    refs = {}
    with torch.no_grad():
        for g, lat in latents.items():
            # synthetic reference voice for EGTTS to clone
            r = xtts.inference(REFERENCE_TEXT, "ar", lat["gpt_cond_latent"], lat["speaker_embedding"], temperature=0.7)
            refs[g] = _wav_bytes(r["wav"])
        for i, (turn, text) in enumerate(sentences.items()):
            lat = latents["male" if i % 2 == 0 else "female"]
            r = xtts.inference(text, "ar", lat["gpt_cond_latent"], lat["speaker_embedding"], temperature=0.7)
            out[f"xtts/{turn}"] = _wav_bytes(r["wav"])
    del xtts
    torch.cuda.empty_cache()

    egtts = _load("OmarSamir/EGTTS-V0.1", config_repo="coqui/XTTS-v2")
    cond = {}
    for g, data in refs.items():
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            f.write(data)
        cond[g] = egtts.get_conditioning_latents(audio_path=[f.name])
        os.unlink(f.name)
    with torch.no_grad():
        for i, (turn, text) in enumerate(sentences.items()):
            gpt, spk = cond["male" if i % 2 == 0 else "female"]
            r = egtts.inference(text, "ar", gpt, spk, temperature=0.75)
            out[f"egtts/{turn}"] = _wav_bytes(r["wav"])
    return out


@app.local_entrypoint()
def main():
    calls = json.loads((HERE.parents[2] / "ml" / "asr" / "test2" / "calls.json").read_text(encoding="utf-8"))["calls"]
    sentences = {f"{c['id']}_{i:02d}": t["text"] for c in calls for i, t in enumerate(c["turns"], 1)}
    clips = generate.remote(sentences)
    for key, data in clips.items():
        dest = HERE / "_clone" / f"{key}.wav"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
    print(f"saved {len(clips)} clips to {HERE / '_clone'}")
