#!/usr/bin/env bash
# ECFD - start the Asterisk PBX on a Mac (Docker Desktop) so phones on the same Wi-Fi /
# hotspot can register and talk with two-way audio.
#
# Usage (from anywhere inside the repo):
#   ./telephony/asterisk/mac-setup.sh              # detects this Mac's IP automatically
#   ./telephony/asterisk/mac-setup.sh 172.20.10.4  # or give the IP yourself
#
# Run it again every time the Mac joins a different network or its IP changes.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
COMPOSE="$REPO/infra/docker-compose.yml"
NAT_FILE="$REPO/telephony/asterisk/pjsip_nat.conf"

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m OK\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERR\033[0m %s\n' "$*"; exit 1; }

# 1. Docker must be running
say "Checking Docker Desktop"
docker info >/dev/null 2>&1 || fail "Docker is not running. Open Docker Desktop, wait for 'Engine running', then run this again."
ok "Docker is running"

# 2. This Mac's address on the current network (the interface that carries the default route)
if [ "${1:-}" != "" ]; then
  IP="$1"
else
  IFACE="$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')"
  IP="$( [ -n "$IFACE" ] && ipconfig getifaddr "$IFACE" 2>/dev/null || true )"
  [ -n "$IP" ] || IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
fi
[ -n "$IP" ] || fail "Could not find this Mac's IP. Connect to the Wi-Fi/hotspot, or pass it: $0 192.168.x.x"
ok "This Mac's IP: $IP"

# 3. Nothing else on the Mac may hold SIP port 5060 (another softphone, an old Asterisk...)
if lsof -nP -iUDP:5060 2>/dev/null | grep -v -i -E 'docker|com.docke|vpnkit' | grep -q UDP; then
  lsof -nP -iUDP:5060 || true
  fail "Another program is using UDP port 5060 (shown above). Quit it and run this again."
fi

# 4. Tell Asterisk which address to give the phones (it runs behind Docker's NAT)
cat > "$NAT_FILE" <<EOF
; Generated by mac-setup.sh on $(date '+%Y-%m-%d %H:%M') - do not commit.
; Phones must be told the Mac's address, not the container's, or calls have no audio.
external_media_address=$IP
external_signaling_address=$IP
; treat every phone as "outside" Docker so the addresses above are always used
local_net=127.0.0.1/32
EOF
ok "Wrote telephony/asterisk/pjsip_nat.conf"

# 5. (Re)start Asterisk so it reads the new address
say "Starting Asterisk (first run downloads the image, ~1 minute)"
docker compose -f "$COMPOSE" up -d --force-recreate asterisk

say "Waiting for Asterisk to be ready"
for _ in $(seq 1 30); do
  if docker exec ecfd-asterisk asterisk -rx "core show version" >/dev/null 2>&1; then break; fi
  sleep 1
done
docker exec ecfd-asterisk asterisk -rx "core show version" >/dev/null 2>&1 || fail "Asterisk did not start. Run: docker logs ecfd-asterisk"
ok "Asterisk is running"

# 6. Prove the address was picked up
if docker exec ecfd-asterisk asterisk -rx "pjsip show transport transport-udp" | grep -q "$IP"; then
  ok "Asterisk will give phones the address $IP"
else
  docker exec ecfd-asterisk asterisk -rx "pjsip show transport transport-udp" || true
  fail "Asterisk did not load the NAT address. Check that pjsip_nat.conf exists and re-run."
fi
docker exec ecfd-asterisk asterisk -rx "pjsip show endpoints" | grep -E "Endpoint:  (1001|1002)" || true

cat <<EOF

------------------------------------------------------------------
 PBX ready. Set up each phone (Linphone) with:
   Username   1001 (employee)   or   1002 (caller)
   Password   employee_pass_1001     attacker_pass_1002
   Domain     $IP
   Transport  UDP
 Test 1: dial 600 from one phone - you should hear yourself (echo).
 Test 2: call 1001 from 1002 and talk both ways for a minute.
 Watch registrations:  docker exec ecfd-asterisk asterisk -rx "pjsip show contacts"
------------------------------------------------------------------
EOF
